apiVersion: v2
name: grafana-agent-metrics
version: 0.1.7
appVersion: v0.18.0
kubeVersion: "^1.16.0-0"
description: Grafana Agent - Metrics
home: https://grafana.com/docs/grafana-cloud/agent/
icon: https://github.com/grafana/agent/raw/main/docs/assets/logo_and_name.png
sources:
  - https://github.com/grafana/agent
maintainers:
  - name: Jiri Tyr
    email: jiri.tyr@gmail.com
engine: gotpl
