{{- $global := . }}
{{- range $k, $v := .Values.channels }}
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  namespace: {{ include "chart.name" $global }}-ch-{{ $k }}
  name: channel
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
  labels: {{- include  "chart.labels" $global | nindent 4 }}
spec:
  type: {{ $v.type }}
  pathname: {{ $v.pathname }}
{{ end }}
