---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: local
  namespace: {{ include "chart.name" . }}
  labels: {{- include  "chart.labels" . | nindent 4 }}
spec:
  clusterSelector:
    matchLabels:
      local-cluster: "true"
