apiVersion: v1
kind: Service
metadata:
  name: {{ template "pronestheus.fullname" . }}
  labels: {{- include "pronestheus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector: {{- include "pronestheus.selectorLabels" . | nindent 4 }}
