apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  labels: {{- include "flux-operator-config.labels" . | nindent 4 }}
spec:
  distribution:
    version: {{ .Values.distribution.version | quote }}
    registry: {{ .Values.distribution.registry | quote }}
  components: {{- toYaml .Values.components | nindent 4 }}
  sync:
    kind: GitRepository
    provider: {{ .Values.sync.provider | quote }}
    url: {{ .Values.sync.url | quote }}
    ref: {{ .Values.sync.ref | quote }}
    path: {{ .Values.sync.path | quote }}
    pullSecret: {{ .Values.sync.pullSecret | quote }}
  {{- with .Values.sync.decryptionSecret }}
  kustomize:
    patches:
      - target:
          kind: Kustomization
          name: flux-system
        patch: |
          apiVersion: kustomize.toolkit.fluxcd.io/v1
          kind: Kustomization
          metadata:
            name: flux-system
            namespace: flux-system
          spec:
            decryption:
              provider: sops
              secretRef:
                name: {{ . }}
  {{- end }}
