{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "libchart.v1.fullname" . }}
  labels: {{- include "libchart.v1.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "libchart.v1.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "libchart.v1.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
